# Generated by Django 5.2.4 on 2025-07-22 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('screenname', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('birthtime', models.TimeField(blank=True, null=True)),
                ('birthplace_lat', models.FloatField()),
                ('birthplace_long', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('autobiography', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=50)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_werman', models.BooleanField(default=False)),
                ('is_wifman', models.BooleanField(default=False)),
            ],
        ),
    ]
