# Generated by Django 5.2.4 on 2025-07-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercharacter',
            old_name='birthplace_long',
            new_name='birthplace_lon',
        ),
    ]
