# Generated by Django 5.2.4 on 2025-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_birthplace_long_playercharacter_birthplace_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercharacter',
            old_name='forename',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='screenname',
            new_name='username',
        ),
    ]
