# Generated by Django 5.2.4 on 2025-08-16 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_playercharacter_birthplace_tz_playercharacter_is_dst'),
        ('socials', '0002_friendship_experiences_together_friendship_game_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accolade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='experiences',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='friends',
            field=models.ManyToManyField(blank=True, through='socials.Friendship', to='characters.playercharacter'),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='private_bio',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='public_bio',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerAccolade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlocked', models.DateTimeField(auto_now_add=True)),
                ('accolade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.accolade')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.playercharacter')),
            ],
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='accolades',
            field=models.ManyToManyField(blank=True, related_name='characters', through='characters.PlayerAccolade', to='characters.accolade'),
        ),
    ]
