# Generated by Django 5.2.4 on 2025-08-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_accolade_playercharacter_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharacter',
            name='user',
        ),
    ]
