# Generated by Django 5.2.4 on 2025-08-16 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='experiences_together',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='game_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
