# Generated by Django 5.2.4 on 2025-07-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('birthtime', models.DateTimeField()),
                ('birthplace_lat', models.FloatField()),
                ('birthplace_long', models.FloatField()),
            ],
        ),
    ]
