# Generated by Django 5.2.4 on 2025-07-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nativity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
