planet_options = [
    {'id': 'planet-sun', 'symbol': '&#9737;', 'name': 'Sun', 'domicileIn': 'Leo', 'exaltedIn': 'Aries', 'exileIn': 'Aquarius', 'fallenIn': 'Libra'},
    {'id': 'planet-moon', 'symbol': '&#9789;', 'name': 'Moon', 'domicileIn': 'Cancer', 'exaltedIn': 'Taurus', 'exileIn': 'Capricorn', 'fallenIn': 'Scorpio'},
    {'id': 'planet-mercury', 'symbol': '&#9791;', 'name': 'Mercury', 'domicileIn': 'Gemini', 'exaltedIn': 'Virgo', 'exileIn': 'Sagittarius', 'fallenIn': 'Pisces'},
    {'id': 'planet-venus', 'symbol': '&#9792;', 'name': 'Venus', 'domicileIn': 'Libra', 'exaltedIn': 'Pisces', 'exileIn': 'Aries', 'fallenIn': 'Virgo'},
    {'id': 'planet-mars', 'symbol': '&#9794;', 'name': 'Mars', 'domicileIn': 'Aries', 'exaltedIn': 'Capricorn', 'exileIn': 'Libra', 'fallenIn': 'Cancer'},
    {'id': 'planet-jupiter', 'symbol': '&#9795;', 'name': 'Jupiter', 'domicileIn': 'Sagittarius', 'exaltedIn': 'Cancer', 'exileIn': 'Gemini', 'fallenIn': 'Capricorn'},
    {'id': 'planet-saturn', 'symbol': '&#9796;', 'name': 'Saturn', 'domicileIn': 'Capricorn', 'exaltedIn': 'Libra', 'exileIn': 'Cancer', 'fallenIn': 'Aries'},
    {'id': 'planet-uranus', 'symbol': '&#9797;', 'name': 'Uranus', 'domicileIn': 'Aquarius', 'exaltedIn': 'Scorpio', 'exileIn': 'Leo', 'fallenIn': 'Taurus'},
    {'id': 'planet-neptune', 'symbol': '&#9798;', 'name': 'Neptune', 'domicileIn': 'Pisces', 'exaltedIn': 'Leo', 'exileIn': 'Virgo', 'fallenIn': 'Aquarius'},
    {'id': 'planet-pluto', 'symbol': '&#9799;', 'name': 'Pluto', 'domicileIn': 'Scorpio', 'exaltedIn': 'Aquarius', 'exileIn': 'Taurus', 'fallenIn': 'Leo'},
]

sign_options = [
    {'id': 'sign-aries', 'symbol': '♈︎', 'name': 'Aries',
        'element': 'Fire (Ig)', 'domicileOf': 'Mars', 'exaltedOf': 'Sun', 'exileOf': 'Venus', 'fallenOf': 'Saturn'},
    {'id': 'sign-taurus', 'symbol': '♉︎', 'name': 'Taurus',
        'element': 'Earth (Tr)', 'domicileOf': 'n/a', 'exaltedOf': 'Moon', 'exileOf': 'Venus', 'fallenOf': 'Saturn'},
    {'id': 'sign-gemini', 'symbol': '♊︎ ', 'name': 'Gemini',
        'element': 'Air (Ae)', 'domicileOf': 'Mercury', 'exaltedOf': 'n/a', 'exileOf': 'Jupiter', 'fallenOf': 'n/a'},
    {'id': 'sign-cancer', 'symbol': '♋︎ ', 'name': 'Cancer',
        'element': 'Water (Aq)', 'domicileOf': 'Moon', 'exaltedOf': 'Jupiter', 'exileOf': 'Saturn', 'fallenOf': 'Mars'},
    {'id': 'sign-leo', 'symbol': '♌︎', 'name': 'Leo',
        'element': 'Fire (Ig)', 'domicileOf': 'Sun', 'exaltedOf': 'Neptune', 'exileOf': 'Uranus', 'fallenOf': 'Pluto'},
    {'id': 'sign-virgo', 'symbol': '♍︎', 'name': 'Virgo',
        'element': 'Earth (Tr)', 'domicileOf': 'n/a', 'exaltedOf': 'Mercury', 'exileOf': 'Neptune', 'fallenOf': 'Venus'},
    {'id': 'sign-libra', 'symbol': '♎︎', 'name': 'Libra',
        'element': 'Air (Ae)', 'domicileOf': 'Venus', 'exaltedOf': 'Saturn', 'exileOf': 'Mars', 'fallenOf': 'Sun'},
    {'id': 'sign-scorpio', 'symbol': '♏︎', 'name': 'Scorpio',
        'element': 'Water (Aq)', 'domicileOf': 'Pluto', 'exaltedOf': 'Uranus', 'exileOf': 'n/a', 'fallenOf': 'Moon'},
    {'id': 'sign-sagittarius', 'symbol': '♐︎', 'name': 'Sagittarius',
        'element': 'Fire (Ig)', 'domicileOf': 'Jupiter', 'exaltedOf': 'n/a', 'exileOf': 'Mercury', 'fallenOf': 'n/a'},
    {'id': 'sign-capricorn', 'symbol': '♑︎', 'name': 'Capricorn',
        'element': 'Earth (Tr)', 'domicileOf': 'Saturn', 'exaltedOf': 'Mars', 'exileOf': 'Moon', 'fallenOf': 'Jupiter'},
    {'id': 'sign-aquarius', 'symbol': '♒︎', 'name': 'Aquarius',
        'element': 'Air (Ae)', 'domicileOf': 'Uranus', 'exaltedOf': 'Pluto', 'exileOf': 'Sun', 'fallenOf': 'Neptune'},
    {'id': 'sign-pisces', 'symbol': '♓︎', 'name': 'Pisces',
        'element': 'Water (Aq)', 'domicileOf': 'Neptune', 'exaltedOf': 'Venus', 'exileOf': 'n/a', 'fallenOf': 'Mercury'},
]

house_options = [
    {'id': 'house-01', 'symbol': '01', 'name': 'Ascendant (Asc.)', 'meaning': 'self, appearance, begeinnings, personality'},
    {'id': 'house-02', 'symbol': '02', 'name': 'House of Value', 'meaning': 'possessions, resources, values, self-worth'},
    {'id': 'house-03', 'symbol': '03', 'name': 'House of Communications', 'meaning': 'communication, siblings, local travel, education'},
    {'id': 'house-04', 'symbol': '04', 'name': 'Imum Coeli (I.C.)', 'meaning': 'home, family, roots, foundations, security'},
    {'id': 'house-05', 'symbol': '05', 'name': 'House of Pleasure', 'meaning': 'creativity, romance, children, recreation'},
    {'id': 'house-06', 'symbol': '06', 'name': 'House of Health', 'meaning': 'health, service, work, daily routine'},
    {'id': 'house-07', 'symbol': '07', 'name': 'Descendant (Desc.)', 'meaning': 'partnerships, marriage, contracts, open enemies'},
    {'id': 'house-08', 'symbol': '08', 'name': 'House of Transformation', 'meaning': 'shared resources, death, rebirth, transformation'},
    {'id': 'house-09', 'symbol': '09', 'name': 'House of Philosophy', 'meaning': 'higher education, philosophy, travel, expansion'},
    {'id': 'house-10', 'symbol': '10', 'name': 'Medium Coeli (M.C.)', 'meaning': 'career, reputation, public status, authority'},
    {'id': 'house-11', 'symbol': '11', 'name': 'House of Community', 'meaning': 'friends, groups, hopes, wishes, humanitarian pursuits'},
    {'id': 'house-12', 'symbol': '12', 'name': 'House of Unconscious', 'meaning': 'hidden things, spirituality, isolation, self-undoing'},
]

moon_point_options = [
    {'id': 'point-orbital-lilith', 'symbol': '&#9912;', 'name': 'Lilith (Apogee)', 'meaning': 'Wifman archetype'},
    {'id': 'point-orbital-priapus', 'symbol': '', 'name': 'Priapus (Perigree)', 'meaning': 'Werman archetype'},
    {'id': 'node-north', 'symbol': '&#9738;', 'name': 'Rahu (N. Node)', 'meaning': 'Future (Descendants)'},
    {'id': 'node-south', 'symbol': '&#9739;', 'name': 'Ketu (S. Node)', 'meaning': 'Past (Ancestors)'},
    {'id': 'point-focal-empty', 'symbol': '', 'name': 'Black Moon (Empty Focus)', 'meaning': ''},
    {'id': 'point-focal-barycenter', 'symbol': '', 'name': 'Barycenter', 'meaning': ''},
]

aspect_options = [
    {'id': 'aspect-conjunct', 'symbol': '&#9740;', 'name': 'Conjunction', 'angle': 0, 'orb': 8, 'meaning': 'Unity, intensified energies'},
    {'id': 'aspect-semisex', 'symbol': '&#9914;', 'name': 'Semisextile', 'angle': 30, 'orb': 4, 'meaning': ''},
    {'id': 'aspect-semisqr', 'symbol': '&#8736;', 'name': 'Semisquare', 'angle': 45, 'orb': 5, 'meaning': ''},
    {'id': 'aspect-sextile', 'symbol': '&#9913;', 'name': 'Sextile', 'angle': 60, 'orb': 6, 'meaning': 'Opportunity, ease, harmony'},
    {'id': 'aspect-quintile', 'symbol': '&#81;', 'name': 'Quintile', 'angle': 72, 'orb': 6, 'meaning': ''},
    {'id': 'aspect-Square', 'symbol': '&#9633;', 'name': 'Square', 'angle': 90, 'orb': 7, 'meaning': 'Tension, challenge, action'},
    {'id': 'aspect-trine', 'symbol': '&#9651;', 'name': 'Trine', 'angle': 120, 'orb': 8, 'meaning': 'Flow, harmony, talent'},
    {'id': 'aspect-sesquiquad', 'symbol': '&#9916;', 'name': 'Sesquiquadrate', 'angle': 135, 'orb': 5, 'meaning': ''},
    {'id': 'aspect-biquint', 'symbol': '&#98;&#81;', 'name': 'Biquintile', 'angle': 144, 'orb': 6, 'meaning': ''},
    {'id': 'aspect-inconjunct', 'symbol': '&#9915;', 'name': 'Inconjunction', 'angle': 150, 'orb': 5, 'meaning': ''},
    {'id': 'aspect-oppose', 'symbol': '&#9741;', 'name': 'Opposition', 'angle': 180, 'orb': 8, 'meaning': 'Awareness, balance, relationship'},
]
