planet_options = [
    {'id': 'planet-sun', 'symbol': '&#9737;', 'name': 'Sun', 'domicileIn': 'Leo', 'exaltedIn': 'Aries', 'exileIn': 'Aquarius', 'fallenIn': 'Libra', 'orbOtt': 10},
    {'id': 'planet-moon', 'symbol': '&#9789;', 'name': 'Moon', 'domicileIn': 'Cancer',
        'exaltedIn': 'Taurus', 'exileIn': 'Capricorn', 'fallenIn': 'Scorpio', 'orbOtt': 10},
    {'id': 'planet-mercury', 'symbol': '&#9791;', 'name': 'Mercury', 'domicileIn': 'Gemini',
        'exaltedIn': 'Virgo', 'exileIn': 'Sagittarius', 'fallenIn': 'Pisces', 'orbOtt': 8},
    {'id': 'planet-venus', 'symbol': '&#9792;', 'name': 'Venus', 'domicileIn': 'Libra',
        'exaltedIn': 'Pisces', 'exileIn': 'Aries', 'fallenIn': 'Virgo', 'orbOtt': 8},
    {'id': 'planet-mars', 'symbol': '&#9794;', 'name': 'Mars', 'domicileIn': 'Aries',
        'exaltedIn': 'Capricorn', 'exileIn': 'Libra', 'fallenIn': 'Cancer', 'orbOtt': 8},
    {'id': 'planet-jupiter', 'symbol': '&#9795;', 'name': 'Jupiter', 'domicileIn': 'Sagittarius',
        'exaltedIn': 'Cancer', 'exileIn': 'Gemini', 'fallenIn': 'Capricorn', 'orbOtt': 6},
    {'id': 'planet-saturn', 'symbol': '&#9796;', 'name': 'Saturn', 'domicileIn': 'Capricorn',
        'exaltedIn': 'Libra', 'exileIn': 'Cancer', 'fallenIn': 'Aries', 'orbOtt': 6},
    {'id': 'planet-uranus', 'symbol': '&#9797;', 'name': 'Uranus', 'domicileIn': 'Aquarius',
        'exaltedIn': 'Scorpio', 'exileIn': 'Leo', 'fallenIn': 'Taurus', 'orbOtt': 4},
    {'id': 'planet-neptune', 'symbol': '&#9798;', 'name': 'Neptune', 'domicileIn': 'Pisces',
        'exaltedIn': 'Leo', 'exileIn': 'Virgo', 'fallenIn': 'Aquarius', 'orbOtt': 4},
    {'id': 'planet-pluto', 'symbol': '&#9799;', 'name': 'Pluto', 'domicileIn': 'Scorpio',
        'exaltedIn': 'Aquarius', 'exileIn': 'Taurus', 'fallenIn': 'Leo', 'orbOtt': 4},
]

planet_order = [planet['name'] for planet in planet_options]

sign_options = [
    {'id': 'sign-aries', 'symbol': '♈︎', 'name': 'Aries',
        'element': 'Fire (Ig)', 'domicileOf': 'Mars', 'exaltedOf': 'Sun', 'exileOf': 'Venus', 'fallenOf': 'Saturn'},
    {'id': 'sign-taurus', 'symbol': '♉︎', 'name': 'Taurus',
        'element': 'Earth (Tr)', 'domicileOf': 'n/a', 'exaltedOf': 'Moon', 'exileOf': 'Venus', 'fallenOf': 'Saturn'},
    {'id': 'sign-gemini', 'symbol': '♊︎ ', 'name': 'Gemini',
        'element': 'Air (Ae)', 'domicileOf': 'Mercury', 'exaltedOf': 'n/a', 'exileOf': 'Jupiter', 'fallenOf': 'n/a'},
    {'id': 'sign-cancer', 'symbol': '♋︎ ', 'name': 'Cancer',
        'element': 'Water (Aq)', 'domicileOf': 'Moon', 'exaltedOf': 'Jupiter', 'exileOf': 'Saturn', 'fallenOf': 'Mars'},
    {'id': 'sign-leo', 'symbol': '♌︎', 'name': 'Leo',
        'element': 'Fire (Ig)', 'domicileOf': 'Sun', 'exaltedOf': 'Neptune', 'exileOf': 'Uranus', 'fallenOf': 'Pluto'},
    {'id': 'sign-virgo', 'symbol': '♍︎', 'name': 'Virgo',
        'element': 'Earth (Tr)', 'domicileOf': 'n/a', 'exaltedOf': 'Mercury', 'exileOf': 'Neptune', 'fallenOf': 'Venus'},
    {'id': 'sign-libra', 'symbol': '♎︎', 'name': 'Libra',
        'element': 'Air (Ae)', 'domicileOf': 'Venus', 'exaltedOf': 'Saturn', 'exileOf': 'Mars', 'fallenOf': 'Sun'},
    {'id': 'sign-scorpio', 'symbol': '♏︎', 'name': 'Scorpio',
        'element': 'Water (Aq)', 'domicileOf': 'Pluto', 'exaltedOf': 'Uranus', 'exileOf': 'n/a', 'fallenOf': 'Moon'},
    {'id': 'sign-sagittarius', 'symbol': '♐︎', 'name': 'Sagittarius',
        'element': 'Fire (Ig)', 'domicileOf': 'Jupiter', 'exaltedOf': 'n/a', 'exileOf': 'Mercury', 'fallenOf': 'n/a'},
    {'id': 'sign-capricorn', 'symbol': '♑︎', 'name': 'Capricorn',
        'element': 'Earth (Tr)', 'domicileOf': 'Saturn', 'exaltedOf': 'Mars', 'exileOf': 'Moon', 'fallenOf': 'Jupiter'},
    {'id': 'sign-aquarius', 'symbol': '♒︎', 'name': 'Aquarius',
        'element': 'Air (Ae)', 'domicileOf': 'Uranus', 'exaltedOf': 'Pluto', 'exileOf': 'Sun', 'fallenOf': 'Neptune'},
    {'id': 'sign-pisces', 'symbol': '♓︎', 'name': 'Pisces',
        'element': 'Water (Aq)', 'domicileOf': 'Neptune', 'exaltedOf': 'Venus', 'exileOf': 'n/a', 'fallenOf': 'Mercury'},
]

house_options = [
    {'id': 'house-01', 'symbol': '01', 'name': 'Ascendant (Asc.)', 'meaning': 'self, appearance, beginnings, personality'},
    {'id': 'house-02', 'symbol': '02', 'name': 'House of Value', 'meaning': 'possessions, resources, values, self-worth'},
    {'id': 'house-03', 'symbol': '03', 'name': 'House of Communications', 'meaning': 'communication, siblings, local travel, education'},
    {'id': 'house-04', 'symbol': '04', 'name': 'Imum Coeli (I.C.)', 'meaning': 'home, family, roots, foundations, security'},
    {'id': 'house-05', 'symbol': '05', 'name': 'House of Pleasure', 'meaning': 'creativity, romance, children, recreation'},
    {'id': 'house-06', 'symbol': '06', 'name': 'House of Health', 'meaning': 'health, service, work, daily routine'},
    {'id': 'house-07', 'symbol': '07', 'name': 'Descendant (Desc.)', 'meaning': 'partnerships, marriage, contracts, open enemies'},
    {'id': 'house-08', 'symbol': '08', 'name': 'House of Transformation', 'meaning': 'shared resources, death, rebirth, transformation'},
    {'id': 'house-09', 'symbol': '09', 'name': 'House of Philosophy', 'meaning': 'higher education, philosophy, travel, expansion'},
    {'id': 'house-10', 'symbol': '10', 'name': 'Medium Coeli (M.C.)', 'meaning': 'career, reputation, public status, authority'},
    {'id': 'house-11', 'symbol': '11', 'name': 'House of Community', 'meaning': 'friends, groups, hopes, wishes, humanitarian pursuits'},
    {'id': 'house-12', 'symbol': '12', 'name': 'House of Unconscious', 'meaning': 'hidden things, spirituality, isolation, self-undoing'},
]

moon_point_options = [
    {'id': 'point-orbital-lilith', 'symbol': '&#9912;',
        'name': 'Lilith (Apogee)', 'meaning': 'Wifman archetype', 'orbOtt': 4},
    {'id': 'point-orbital-priapus', 'symbol': '',
        'name': 'Priapus (Perigree)', 'meaning': 'Werman archetype', 'orbOtt': 4},
    {'id': 'node-north', 'symbol': '&#9738;',
        'name': 'Rahu (N. Node)', 'meaning': 'Future (Descendants)', 'orbOtt': 4},
    {'id': 'node-south', 'symbol': '&#9739;',
        'name': 'Ketu (S. Node)', 'meaning': 'Past (Ancestors)', 'orbOtt': 4},
    {'id': 'point-focal-empty', 'symbol': '',
        'name': 'Black Moon (Empty Focus)', 'meaning': '', 'orbOtt': 4},
    {'id': 'point-focal-barycenter', 'symbol': '',
        'name': 'Barycenter', 'meaning': '', 'orbOtt': 4},
]

aspect_options = [
    {'id': 'aspect-conjunct', 'symbol': '&#9740;', 'name': 'Conjunction', 'angle': 0,
        'orb': 8, 'meaning': 'Unity, intensified energies', 'color': 'rgba(var(--quiTi), 1)'},
    {'id': 'aspect-semisex', 'symbol': '&#9914;', 'name': 'Semisextile',
        'angle': 30, 'orb': 4, 'meaning': '', 'color': 'rgba(var(--priTi), 1)'},
    # {'id': 'aspect-semisqr', 'symbol': '&#8736;', 'name': 'Semisquare',
    #     'angle': 45, 'orb': 5, 'meaning': '', 'color': 'rgba(var(--secTi), 1)'},
    {'id': 'aspect-sextile', 'symbol': '&#9913;', 'name': 'Sextile', 'angle': 60,
        'orb': 6, 'meaning': 'Opportunity, ease, harmony', 'color': 'rgba(var(--terTi), 1)'},
    # {'id': 'aspect-quintile', 'symbol': '&#81;', 'name': 'Quintile',
    #     'angle': 72, 'orb': 6, 'meaning': '', 'color': 'rgba(var(--terTi), 1)'},
    {'id': 'aspect-Square', 'symbol': '&#9633;', 'name': 'Square', 'angle': 90, 'orb': 7,
        'meaning': 'Tension, challenge, action', 'color': 'rgba(var(--quaTi), 1)'},
    {'id': 'aspect-trine', 'symbol': '&#9651;', 'name': 'Trine', 'angle': 120,
        'orb': 8, 'meaning': 'Flow, harmony, talent', 'color': 'rgba(var(--quiTi), 1)'},
    # {'id': 'aspect-sesquiquad', 'symbol': '&#9916;', 'name': 'Sesquiquadrate',
    #     'angle': 135, 'orb': 5, 'meaning': '', 'color': 'rgba(var(--secTi), 1)'},
    # {'id': 'aspect-biquint', 'symbol': '&#98;&#81;', 'name': 'Biquintile',
    #     'angle': 144, 'orb': 6, 'meaning': '', 'color': 'rgba(var(--terTi), 1)'},
    {'id': 'aspect-inconjunct', 'symbol': '&#9915;', 'name': 'Inconjunction',
        'angle': 150, 'orb': 5, 'meaning': '', 'color': 'rgba(var(--secTi), 1)'},
    {'id': 'aspect-oppose', 'symbol': '&#9741;', 'name': 'Opposition', 'angle': 180, 'orb': 8,
        'meaning': 'Awareness, balance, relationship', 'color': 'rgba(var(--quiTi), 1)'},
]

constellation_options = [
    # Arietisids
    {'id': 'constellation-ari', 'name': 'Aries', 'angle': 1,
        'angleDegree': 0, 'govSign': 'Aries', 'distinction': 'Self', 'natalHouse': 'house-01'},
    {'id': 'constellation-cep', 'name': 'Cepheus', 'decan': 1, 'decanDegree': 5,
        'constellationCentroidDegree': 0, 'distinction': 'Father', 'govSign': 'Aries', 'natalHouse': 'house-01'},
    {'id': 'constellation-cas', 'name': 'Cassiopeia', 'decan': 2, 'decanDegree': 15,
        'constellationCentroidDegree': 0, 'distinction': 'Mother', 'govSign': 'Aries', 'natalHouse': 'house-01'},
    {'id': 'constellation-and', 'name': 'Andromeda', 'decan': 3, 'decanDegree': 25,
        'constellationCentroidDegree': 15, 'distinction': 'Child', 'govSign': 'Aries', 'natalHouse': 'house-01'},
    # Taurids
    {'id': 'constellation-tau', 'name': 'Taurus', 'angle': 2,
        'angleDegree': 30, 'govSign': 'Taurus', 'distinction': 'Worth', 'natalHouse': 'house-02'},
    {'id': 'constellation-cet', 'name': 'Cetus', 'decan': 4, 'decanDegree': 35,
        'constellationCentroidDegree': 15, 'distinction': 'Leviathan', 'govSign': 'Taurus', 'natalHouse': 'house-02'},
    {'id': 'constellation-tri', 'name': 'Triangulum', 'decan': 5, 'decanDegree': 45,
        'constellationCentroidDegree': 30, 'distinction': 'Equilibrium', 'govSign': 'Taurus', 'natalHouse': 'house-02'},
    {'id': 'constellation-per', 'name': 'Perseus', 'decan': 6, 'decanDegree': 55,
        'constellationCentroidDegree': 45, 'distinction': 'Beastslayer', 'govSign': 'Taurus', 'natalHouse': 'house-02'},
    # Geminids
    {'id': 'constellation-gem', 'name': 'Gemini', 'angle': 31,
        'angleDegree': 60, 'govSign': 'Gemini', 'distinction': 'Education', 'natalHouse': 'house-03'},
    {'id': 'constellation-eri', 'name': 'Eridanus', 'decan': 7, 'decanDegree': 65,
        'constellationCentroidDegree': 60, 'distinction': 'Abyss', 'govSign': 'Gemini', 'natalHouse': 'house-03'},
    {'id': 'constellation-ori', 'name': 'Orion', 'decan': 8, 'decanDegree': 75,
        'constellationCentroidDegree': 75, 'distinction': 'Huntsman', 'govSign': 'Gemini', 'natalHouse': 'house-03'},
    {'id': 'constellation-aur', 'name': 'Auriga', 'decan': 9, 'decanDegree': 85,
        'constellationCentroidDegree': 90, 'distinction': 'Charioteer', 'govSign': 'Gemini', 'natalHouse': 'house-03'},
    # Cancrids
    {'id': 'constellation-cnc', 'name': 'Cancer', 'angle': 4,
        'angleDegree': 90, 'govSign': 'Cancer', 'distinction': 'Home', 'natalHouse': 'house-04'},
    {'id': 'constellation-lep', 'name': 'Lepus', 'decan': 10, 'decanDegree': 95,
        'constellationCentroidDegree': 90, 'distinction': 'Scapegoat', 'govSign': 'Cancer', 'natalHouse': 'house-04'},
    {'id': 'constellation-cma', 'name': 'Canis Major', 'decan': 11, 'decanDegree': 105,
        'constellationCentroidDegree': 105, 'distinction': 'Foxhound', 'govSign': 'Cancer', 'natalHouse': 'house-04'},
    {'id': 'constellation-cmi', 'name': 'Canis Minor', 'decan': 12, 'decanDegree': 115,
        'constellationCentroidDegree': 105, 'distinction': 'Sheepdog', 'govSign': 'Cancer', 'natalHouse': 'house-04'},
    # Leonids
    {'id': 'constellation-leo', 'name': 'Leo', 'angle': 5,
        'angleDegree': 120, 'govSign': 'Leo', 'distinction': 'Creativity', 'natalHouse': 'house-05'},
    {'id': 'constellation-arg', 'name': 'Argo Navis', 'decan': 13, 'decanDegree': 125,
        'constellationCentroidDegree': 150, 'distinction': 'Dreadnought', 'govSign': 'Leo', 'natalHouse': 'house-05'},
    {'id': 'constellation-hya', 'name': 'Hydra', 'decan': 14, 'decanDegree': 135,
        'constellationCentroidDegree': 150, 'distinction': 'Seaserpent', 'govSign': 'Leo', 'natalHouse': 'house-05'},
    {'id': 'constellation-uma', 'name': 'Ursa Major', 'decan': 15, 'decanDegree': 145,
        'constellationCentroidDegree': 165, 'distinction': 'Bugbear', 'govSign': 'Leo', 'natalHouse': 'house-05'},
    # Virginids
    {'id': 'constellation-vir', 'name': 'Virgo', 'angle': 6,
        'angleDegree': 150, 'govSign': 'Virgo', 'distinction': 'Service', 'natalHouse': 'house-06'},
    {'id': 'constellation-crt', 'name': 'Crater', 'decan': 16, 'decanDegree': 155,
        'constellationCentroidDegree': 165, 'distinction': 'Waterjug', 'govSign': 'Virgo', 'natalHouse': 'house-06'},
    {'id': 'constellation-crv', 'name': 'Corvus', 'decan': 17, 'decanDegree': 165,
        'constellationCentroidDegree': 180, 'distinction': 'Trickster', 'govSign': 'Virgo', 'natalHouse': 'house-06'},
    {'id': 'constellation-cen', 'name': 'Centaurus', 'decan': 18, 'decanDegree': 175, 'constellationCentroidDegree': 195, 'distinction': 'Marauder', 'govSign': 'Virgo', 'natalHouse': 'house-06'},
    # Librids
    {'id': 'constellation-lib', 'name': 'Libra', 'angle': 7,
        'angleDegree': 180, 'govSign': 'Libra', 'distinction': 'Cooperation', 'natalHouse': 'house-07'},
    {'id': 'constellation-boo', 'name': 'Boötes', 'decan': 19, 'decanDegree': 185,
        'constellationCentroidDegree': 210, 'distinction': 'Oxherd', 'govSign': 'Libra', 'natalHouse': 'house-07'},
    {'id': 'constellation-crb', 'name': 'Corona Borealis', 'decan': 20, 'decanDegree': 195,
        'constellationCentroidDegree': 225, 'distinction': 'Hellish Crown', 'govSign': 'Libra', 'natalHouse': 'house-07'},
    {'id': 'constellation-umi', 'name': 'Ursa Minor', 'decan': 21, 'decanDegree': 205,
        'constellationCentroidDegree': 225, 'distinction': 'Bearcub', 'govSign': 'Libra', 'natalHouse': 'house-07'},
    # Scorpiids
    {'id': 'constellation-sco', 'name': 'Scorpio', 'angle': 8,
        'angleDegree': 210, 'govSign': 'Scorpio', 'distinction': 'Regeneration', 'natalHouse': 'house-08'},
    {'id': 'constellation-ser', 'name': 'Serpens', 'decan': 22, 'decanDegree': 215,
        'constellationCentroidDegree': 240, 'distinction': 'Snake-in-a-Basket', 'govSign': 'Scorpio', 'natalHouse': 'house-08'},
    {'id': 'constellation-lup', 'name': 'Lupus', 'decan': 23, 'decanDegree': 225,
        'constellationCentroidDegree': 240, 'distinction': 'Wolf', 'govSign': 'Scorpio', 'natalHouse': 'house-08'},
    {'id': 'constellation-her', 'name': 'Hercules', 'decan': 24, 'decanDegree': 235,
        'constellationCentroidDegree': 255, 'distinction': 'Strongman', 'govSign': 'Scorpio', 'natalHouse': 'house-08'},
    # Sagitariids
    {'id': 'constellation-sgr', 'name': 'Sagittarius', 'angle': 9,
        'angleDegree': 240, 'govSign': 'Sagittarius', 'distinction': 'Enterprise', 'natalHouse': 'house-09'},
    {'id': 'constellation-dra', 'name': 'Draco', 'decan': 25, 'decanDegree': 245,
        'constellationCentroidDegree': 255, 'distinction': 'Dragon', 'govSign': 'Sagittarius', 'natalHouse': 'house-09'},
    {'id': 'constellation-oph', 'name': 'Ophiuchus', 'decan': 26, 'decanDegree': 255,
        'constellationCentroidDegree': 255, 'distinction': 'Snakecharmer', 'govSign': 'Sagittarius', 'natalHouse': 'house-09'},
    {'id': 'constellation-ara', 'name': 'Ara', 'decan': 27, 'decanDegree': 265,
        'constellationCentroidDegree': 255, 'distinction': 'Altar', 'govSign': 'Sagittarius', 'natalHouse': 'house-09'},
    # Capricrids
    {'id': 'constellation-cap', 'name': 'Capricorn', 'angle': 10,
        'angleDegree': 270, 'govSign': 'Capricorn', 'distinction': 'Career', 'natalHouse': 'house-10'},
    {'id': 'constellation-lyra', 'decan': 28, 'decanDegree': 275,
        'constellationCentroidDegree': 270, 'distinction': 'Fallen Eagle', 'govSign': 'Capricorn', 'natalHouse': 'house-10'},
    {'id': 'constellation-aql', 'name': 'Aquila', 'decan': 29, 'decanDegree': 285,
        'constellationCentroidDegree': 285, 'distinction': 'Exalted Eagle', 'govSign': 'Capricorn', 'natalHouse': 'house-10'},
    {'id': 'constellation-cra', 'name': 'Corona Australis', 'decan': 30, 'decanDegree': 295,
        'constellationCentroidDegree': 285, 'distinction': 'Heavenly Crown', 'govSign': 'Capricorn', 'natalHouse': 'house-10'},
    # Aquariids
    {'id': 'constellation-aqr', 'name': 'Aquarius', 'angle': 11,
        'angleDegree': 300, 'govSign': 'Aquarius', 'distinction': 'Reward', 'natalHouse': 'house-11'},
    {'id': 'constellation-cyg', 'name': 'Cygnus', 'decan': 31, 'decanDegree': 305,
        'constellationCentroidDegree': 300, 'distinction': 'Swansong', 'govSign': 'Aquarius', 'natalHouse': 'house-11'},
    {'id': 'constellation-sge', 'name': 'Sagitta', 'decan': 32, 'decanDegree': 315,
        'constellationCentroidDegree': 300, 'distinction': 'Ordnance', 'govSign': 'Aquarius', 'natalHouse': 'house-11'},
    {'id': 'constellation-del', 'name': 'Delphinus', 'decan': 33, 'decanDegree': 325,
        'constellationCentroidDegree': 315, 'distinction': 'Flying Fish', 'govSign': 'Aquarius', 'natalHouse': 'house-11'},
    # Pisciids
    {'id': 'constellation-psc', 'name': 'Pisces', 'angle': 12,
        'angleDegree': 330, 'govSign': 'Pisces', 'distinction': 'Reprisal', 'natalHouse': 'house-12'},
    {'id': 'constellation-eql', 'name': 'Equuleus', 'decan': 34, 'decanDegree': 335,
        'constellationCentroidDegree': 315, 'distinction': 'Old Pony', 'govSign': 'Pisces', 'natalHouse': 'house-12'},
    {'id': 'constellation-peg', 'name': 'Pegasus', 'decan': 35, 'decanDegree': 345,
        'constellationCentroidDegree': 345, 'distinction': 'Warhorse', 'govSign': 'Pisces', 'natalHouse': 'house-12'},
    {'id': 'constellation-psa', 'name': 'Piscis Austrinus', 'decan': 36, 'decanDegree': 355,
        'constellationCentroidDegree': 345, 'distinction': 'Fish-in-a-Bowl', 'govSign': 'Pisces', 'natalHouse': 'house-12'},
]
